---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 5000
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password 
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@db-service:5432/guests_db
            - name: FLASK_ENV
              value: development
          image: docker.io/library/guest_app_k8s-backend:latest
          imagePullPolicy: IfNotPresent
          name: backend-container
          ports:
            - containerPort: 5000
              protocol: TCP
