---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-cloud
  labels:
    type: cloud

spec:
  storageClassName: azure-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
